config/routes.rb
Rails.application.routes.draw do
  get 'buskado/show'
  get '/buskado', to: 'buskado#show', as: 'buskado'

  namespace :traduktor_ortografiko, path: "traduktor-ortografiko" do
    get 'fonologiko', to: 'traduktor_ortografiko#fonologiko'
    post 'fonologiko', to: 'traduktor_ortografiko#post_fonologiko'

    get 'etimologiko', to: 'traduktor_ortografiko#etimologiko'
    post 'etimologiko', to: 'traduktor_ortografiko#post_etimologiko'

    root 'traduktor_ortografiko#fonologiko'
  end


  root "buskado#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/orthographic_translator_service.rb
class OrthographicTranslatorService
  API_PATH = 'https://palabra.papiamentu.info/api/v1/palabra'

  def call(text, target_orthographic)
    words = text.split

    words_in_target_orthographic = []

    words.each do |word|
      words_in_target_orthographic << get_variant(word, target_orthographic)
    end

    words_in_target_orthographic.join(' ')
  end

  def get_variant(word, target_orthographic)
    variant = "#{word}*"

    word.delete!('.(),')

    uri = URI.parse(URI::DEFAULT_PARSER.escape "#{API_PATH}/#{word}")
    response = HTTParty.get(uri)
    data = JSON.parse response.body

    return variant if data['variants'].nil?

    word_is_pap = !(data['variants'].select { |v| v['orthographic_type'] == 'pap' && v['lemma'].downcase == word.downcase }.empty?)

    return word if word_is_pap

    target_orthographic_variants = data['variants'].select { |v| v['orthographic_type'] == target_orthographic }

    if target_orthographic_variants.empty?
      variant
    else
      target_orthographic_variants.first['lemma']
    end
  end
end

app/models/papiamentu_variants_service.rb
class PapiamentuVariantsService
  API_PATH = 'https://palabra.papiamentu.info/api/v1/palabra'

  def call(query)
    words = query.split

    query_with_variants = []
    words_with_variants = []

    words.each do |word|
      variants = variants_for(word)
      query_with_variants << "(#{variants.join(' OR ')})"
      words_with_variants << variants
    end

    query_with_variants = query_with_variants.join(' AND ')

    {
      query_with_variants: query_with_variants,
      words_with_variants: words_with_variants
    }
  end

  def variants_for(word)
    variants = [word]

    uri = URI.parse(URI::DEFAULT_PARSER.escape "#{API_PATH}/#{word}")
    response = HTTParty.get(uri)
    data = JSON.parse response.body

    return variants if data['variants'].nil?

    data['variants'].each do |variant|
      variants << variant['lemma'] unless variants.include? variant['lemma']
    end
    variants
  end
end

app/models/search_service.rb
class SearchService
  def call(query, start = 1, options = '')
    search_data = {}

    search_data[:query] = query
    search_data[:start] = start

    # PapiamentuVariantsService Adds query_with_variants
    # and words_with_variants to search_data
    search_data.merge!(PapiamentuVariantsService.new.call(query))

    search_data[:query_with_variants] += " #{options}"

    searcher = Google::Apis::CustomsearchV1::CustomSearchAPIService.new
    searcher.key = Rails.application.credentials.google[:search_client_key]

    search_data[:results] = searcher.list_cses(
      q: search_data[:query_with_variants],
      cx: Rails.application.credentials.google[:search_client_cx],
      start: start
    )

    search_data
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buskado_controller.rb
class BuskadoController < ApplicationController
  def show
    @query = params[:query].nil? ? '' : params[:query]
    @elimina_otro_idioma = 'AND (esaki OR esei OR aki) -la -los -las'
    @search_data = nil

    return if @query.empty?

    @search_data = SearchService.new.call(
      @query,
      params[:start].nil? ? 1 : params[:start].to_i,
      @elimina_otro_idioma
    )
  end
end

app/controllers/traduktor_ortografiko/traduktor_ortografiko_controller.rb
module TraduktorOrtografiko
  class TraduktorOrtografikoController < ApplicationController
    def fonologiko
      @teksto = params[:teksto] || ""
      @resultado = OrthographicTranslatorService.new.call(
        @teksto,
        "aw"
      )
    end

    def post_fonologiko
      @resultado = OrthographicTranslatorService.new.call(
        params[:teksto],
        "cw"
      )

      render turbo_stream: turbo_stream.replace(
        "output_area",
        partial: "traduktor_ortografiko/output",
        locals: {
          resultado: @resultado
        }
      )
    end

    def etimologiko
      @teksto = params[:teksto] || ""
      @resultado = OrthographicTranslatorService.new.call(
        @teksto,
        "cw"
      )
    end

    def post_etimologiko
      @resultado = OrthographicTranslatorService.new.call(
        params[:teksto],
        "aw"
      )

      render turbo_stream: turbo_stream.replace(
        "output_area",
        partial: "traduktor_ortografiko/output",
        locals: {
          resultado: @resultado
        }
      )
    end


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bold_search_words(snippet, words)
    snippet.split.collect { |w|
      words.include?(w.downcase.delete('.()",')) ? "<b>#{w}</b>" : w
    }.join(' ').html_safe
  end
end

app/helpers/buskado_helper.rb
module BuskadoHelper
end

app/helpers/traduktor_ortografiko_helper.rb
module TraduktorOrtografikoHelper
end

app/views/buskado/show.html.erb
<%= content_for :heading_title, "Motor di búskeda inteligente (cross-orthographic)" %>

<div class="container max-auto p-2">
  <div class="md:w-[584px] mt-7 flex items-center rounded-full border hover:shadow-md">
    <div class="pl-5">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
    </div>
    <%= form_tag("/buskado", method: "get") do %>
      <input value="<%= @query %>" type="text" name="query" type="text" class="border-none focus:ring-transparent w-full bg-transparent rounded-full py-[14px] pl-4 outline-none" />
    <% end %>
  </div>
</div>

<% unless @search_data.nil? %>
  <div class="container max-auto p-2">
    <div class="px-3">
      <p class="text-gray-500 text-md mb-5 mt-3">Serka <%= @search_data[:results].search_information.total_results %> resultado</p>
      <% unless @search_data[:results].items.nil? %>
        <% @search_data[:results].items.each do |item| %>
          <div class="max-w-xl mb-8 font-sans">
            <div class="group">
              <a href="<%= item.link %>" class="text-sml font-OpenSans text-stone-900">
                <%= item.link %>
              </a>
              <a href="<%= item.link %>">
                <h2 class="truncate text-xl text-blue-700 group-hover:underline font-OpenSans">
                  <%= raw item.title %>​
                </h2>
              </a>
            </div>
            <p class="line-clamp-2 text-gray-900 font-OpenSans">​
              <%= bold_search_words(item.snippet, @search_data[:words_with_variants].flatten) %>
            </p>
          </div>
        <% end %>
      <% end %>
    <div>
  </div>
<% end %>

<% unless @search_data.nil? %>
  <div class="container max-auto p-2">
    <nav class="flex max-w-xl items-center justify-between border-t border-gray-200 px-4 sm:px-0">
      <div class="hidden md:-mt-px md:flex">
        <% 0.upto(@search_data[:results].search_information.total_results.to_i / 10) do |i| %>
            <li class="<%= (@search_data[:start] == (i * 10) + 1) ? "inline-flex items-center border-t-2 border-indigo-500 px-4 pt-4 text-sm font-medium text-indigo-600" : "inline-flex items-center border-t-2 border-transparent px-4 pt-4 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700" %>"><a href="/buskado?utf8=✓&query=<%= @query %>&start=<%= (i * 10) + 1 %>"><%= i + 1 %></a></li>
            <% break if i >= 10 %>
          <% end %>
      </div>
    </nav>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABClink</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.cdnfonts.com/css/product-sans" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/6.5.95/css/materialdesignicons.min.css" />
  </head>
  <body class="container mx-auto bg-white">
    <%= render "shared/nav" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<div class="flex">
  <header class="flex flex-grow px-5 py-2 border-b border-gray-200">
    <!-- Menu and Logo -->
    <div class="flex-none">
      <div class="flex flex-grow mt-1">
        <h1><strong><span style="font-family: 'Product Sans',sans-serif;font-size:20px;"><span class="a-blue">A</span><span
          class="b-blue">B</span><span class="c-blue">C</span><span class="link-yellow">link</span></span></strong></h1>
          <div class="ml-2 my-auto text-lg font-medium text-gray-500">
            <%= yield :heading_title %>
          </div>
      </div>
    </div>
    <div class="flex-grow"></div>
  </header>
</div>

app/views/traduktor_ortografiko/_output.html.erb
<div id="output_area" class="text-base lg:text-2xl text-black h-10">
  <%= resultado %>
</div>

app/views/traduktor_ortografiko/traduktor_ortografiko/etimologiko.html.erb
<%= content_for :heading_title, "Traduktor Ortográfiko" %>

<!-- Translator -->
<div class="before:content-[''] before:bg-gray-50
      before:h-24 before:w-full before:absolute
      before:border-b before:border-gray-200
      before:z-0 z-10">
  <div class="container mx-auto px-0 lg:px-24">
    <div class="flex flex-row mt-16">
      <div class="pb-4 top-32 h z-10 w-full">
        <!-- Translator Container -->
        <div class="bg-white rounded-lg border border-gray-200
            drop-shadow-sm shadow-sm">
          <!-- Language Bar -->
          <div class="flex border-b border-gray-300">
            <!-- From Languages -->
            <div class="w-7/12">
              <nav class="flex flex-row rounded-tl-lg">
                <!-- Lang: English -->
                <button class="uppercase py-3.5 px-3
                    text-gray-600 font-semibold
                    text-xs lg:text-sm
                    hover:bg-gray-50 hover:text-gray-700
                    transition-colors duration-100
                    text-blue-500 hover:text-blue-600
                    border-b-2 border-blue-500 ">
                    Ortografia etimológiko
                  </button>
              </nav>
            </div>

            <!-- Switch Languages -->
            <div class="w-1/12">
              <div class="flex items-center justify-center">
                <%= button_to traduktor_ortografiko_fonologiko_path, method: :get, params: { teksto: @resultado }, class: "hover:bg-gray-100 rounded-full w-10 h-10 mt-1 transition-colors duration-100" do %>
                  <i class="mdi mdi-swap-horizontal mdi-24px text-gray-600"></i>
                <% end %>
              </div>
            </div>

            <!-- To Languages -->
            <div class="w-7/12">
              <nav class="flex flex-row rounded-tl-lg">
                <button class="uppercase py-3.5 px-3
                    text-gray-600 font-semibold
                    text-xs lg:text-sm
                    hover:bg-gray-50 hover:text-gray-700
                    transition-colors duration-100
                    text-blue-500 hover:text-blue-600
                    border-b-2 border-blue-500 ">
                    Ortografia fonológiko
                  </button>
              </nav>
            </div>
          </div>

          <!-- Translate Inputs -->
          <div class="flex">
            <!-- Input Container -->
            <div class="w-6/12 border-r border-gray-200 p-4">
              <div class="h-40">
                <div class="flex flex-row">
                  <%= form_tag "/traduktor-ortografiko/fonologiko",
                    method: "post",
                    data: { controller: "form" } do %>
                    <%= text_area_tag :teksto,
                      @teksto,
                      class: "border-none focus:ring-transparent resize-none w-full focus:outline-none text-base lg:text-2xl text-blak custom-scrollbar",
                      rows: "5",
                      spellcheck: "false",
                      maxlength: "5000",
                      data: { action: "keyup->form#submit" }
                    %>
                  <% end %>
                </div>
              </div>

              <!-- Input Buttons -->
              <div class="h-10">
                <div class="flex flex-grow">
                  <div class="flex-none">
                  </div>

                  <div class="grow">
                    <div class="flex float-right">
                      <div class="text-sm text-gray-400 pt-5"
                        x-text="`${sourceText.length}/5000`">
                        0/5000
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Output Container -->
            <div class="w-6/12 bg-gray-100 rounded-br-lg p-4">
              <div class="h-40">
                <!-- Output Area -->
                <%= render "traduktor_ortografiko/output", resultado: @resultado %>
              </div>

              <!-- Output Buttons -->
              <div class="h-10">
                <div class="flex flex-grow" x-show="sourceText.length">
                  <div class="grow">
                    <div class="flex float-right">
                      <button id="copy-translation" class="hover:bg-gray-200 rounded-full
                            w-10 h-10 mt-1
                            transition-colors duration-100" :data-clipboard-text="translatedText"
                          x-on:click="Toastify({text: 'Translation copied to your clipboard.', className: 'success rounded-md'}).showToast()">
                          <i class="mdi mdi-content-copy mdi-18px text-gray-600"></i>
                        </button>

                      <button class="hover:bg-gray-200 rounded-full
                          w-10 h-10 mt-1
                          transition-colors duration-100">
                          <i class="mdi mdi-share-variant mdi-18px text-gray-600"></i>
                        </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/traduktor_ortografiko/traduktor_ortografiko/fonologiko.html.erb
<%= content_for :heading_title, "Traduktor Ortográfiko" %>

<!-- Translator -->
<div class="before:content-[''] before:bg-gray-50
      before:h-24 before:w-full before:absolute
      before:border-b before:border-gray-200
      before:z-0 z-10">
  <div class="container mx-auto px-0 lg:px-24">
    <div class="flex flex-row mt-16">
      <div class="pb-4 top-32 h z-10 w-full">
        <!-- Translator Container -->
        <div class="bg-white rounded-lg border border-gray-200
            drop-shadow-sm shadow-sm">
          <!-- Language Bar -->
          <div class="flex border-b border-gray-300">
            <!-- From Languages -->
            <div class="w-7/12">
              <nav class="flex flex-row rounded-tl-lg">
                <!-- Lang: English -->
                <button class="uppercase py-3.5 px-3
                    text-gray-600 font-semibold
                    text-xs lg:text-sm
                    hover:bg-gray-50 hover:text-gray-700
                    transition-colors duration-100
                    text-blue-500 hover:text-blue-600
                    border-b-2 border-blue-500 ">
                    Ortografia fonológiko
                  </button>
              </nav>
            </div>

            <!-- Switch Languages -->
            <div class="w-1/12">
              <div class="flex items-center justify-center">
                <%= button_to traduktor_ortografiko_etimologiko_path, method: :get, params: { teksto: @resultado }, class: "hover:bg-gray-100 rounded-full w-10 h-10 mt-1 transition-colors duration-100" do %>
                  <i class="mdi mdi-swap-horizontal mdi-24px text-gray-600"></i>
                <% end %>
              </div>
            </div>

            <!-- To Languages -->
            <div class="w-7/12">
              <nav class="flex flex-row rounded-tl-lg">
                <button class="uppercase py-3.5 px-3
                    text-gray-600 font-semibold
                    text-xs lg:text-sm
                    hover:bg-gray-50 hover:text-gray-700
                    transition-colors duration-100
                    text-blue-500 hover:text-blue-600
                    border-b-2 border-blue-500 ">
                    Ortografia etimológiko
                  </button>
              </nav>
            </div>
          </div>

          <!-- Translate Inputs -->
          <div class="flex">
            <!-- Input Container -->
            <div class="w-6/12 border-r border-gray-200 p-4">
              <div class="h-40">
                <div class="flex flex-row">
                  <!-- Input Area -->
                  <%= form_tag "/traduktor-ortografiko/etimologiko",
                    method: "post",
                    data: { controller: "form" } do %>
                    <%= text_area_tag :teksto,
                      @teksto,
                      class: "border-none focus:ring-transparent resize-none w-full focus:outline-none text-base lg:text-2xl text-blak custom-scrollbar",
                      rows: "5",
                      spellcheck: "false",
                      maxlength: "5000",
                      data: { action: "keyup->form#submit" }
                    %>
                  <% end %>
                </div>
              </div>

              <!-- Input Buttons -->
              <div class="h-10">
                <div class="flex flex-grow">
                  <div class="flex-none">
                  </div>

                  <div class="grow">
                    <div class="flex float-right">
                      <div class="text-sm text-gray-400 pt-5"
                        x-text="`${sourceText.length}/5000`">
                        0/5000
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Output Container -->
            <div class="w-6/12 bg-gray-100 rounded-br-lg p-4">
              <div class="h-40">
                <!-- Output Area -->
                <%= render "traduktor_ortografiko/output", resultado: @resultado %>
              </div>

              <!-- Output Buttons -->
              <div class="h-10">
                <div class="flex flex-grow" x-show="sourceText.length">
                  <div class="grow">
                    <div class="flex float-right">
                      <button id="copy-translation" class="hover:bg-gray-200 rounded-full
                            w-10 h-10 mt-1
                            transition-colors duration-100" :data-clipboard-text="translatedText"
                          x-on:click="Toastify({text: 'Translation copied to your clipboard.', className: 'success rounded-md'}).showToast()">
                          <i class="mdi mdi-content-copy mdi-18px text-gray-600"></i>
                        </button>

                      <button class="hover:bg-gray-200 rounded-full
                          w-10 h-10 mt-1
                          transition-colors duration-100">
                          <i class="mdi mdi-share-variant mdi-18px text-gray-600"></i>
                        </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>